ARG SPARK_VERSION
ARG HADOOP_VERSION
FROM guangie88/spark-custom-addons:${SPARK_VERSION}_hadoop-${HADOOP_VERSION}_hive_pyspark_debian

ARG PACKAGE_SET=standard

RUN set -euo pipefail && \
    # Install build deps
    apt-get update; \
    apt-get install -y --no-install-recommends \
        libgeos-dev \
        build-essential \
        python-dev \
        python-pip \
        python-setuptools \
        python3-dev \
        python3-pip \
        python3-setuptools \
        ; \
    # Install pip packages - the left-to-right order matters
    if [ "${PACKAGE_SET}" = "standard" ]; then \
        PACKAGES="numpy pandas pyproj shapely requests"; \
    fi; \
    ## Python 2
    python2 -m pip install --no-cache-dir --no-binary=:all: wheel; \
    for PACKAGE in ${PACKAGES}; do \
        python2 -m pip install --no-cache-dir --no-binary=:all: ${PACKAGE}; \
    done; \
    python2 -m pip uninstall -y wheel; \
    ## Python 3
    python3 -m pip install --no-cache-dir --no-binary=:all: wheel; \
    for PACKAGE in ${PACKAGES}; do \
        python3 -m pip install --no-cache-dir --no-binary=:all: ${PACKAGE}; \
    done; \
    python3 -m pip uninstall -y wheel; \
    # Add required runtime libraries
    apt-get install -y --no-install-recommends \
        libgeos-c1v5 \
        ; \
    # Clean up build deps
    apt-get remove -y \
        build-essential \
        libgeos-dev \
        python-dev \
        python-pip \
        python3-pip \
        python-setuptools \
        ; \
    apt-get autoremove -y; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/*; \
    :
